config:
  mlflow:
    tracking_uri: http://mlflow:5001
    experiment_name: sales_forecasting
    registry_name: sales_forecast_models

  models:
    xgboost:
      params:
        n_estimators: 100
        max_depth: 5
        learning_rate: 0.1
        objective: "reg:squarederror"
        subsample: 0.8
        lambda: 1.5
        random_state: 42

    lightgbm:
      params:
        num_leaves: 31
        max_depth: 5
        learning_rate: 0.1
        n_estimators: 100
        objective: regression
        random_state: 42

    prophet:
      enabled: false
      params:
        seasonality_mode: multiplicative
        changepoint_prior_scale: 0.05
        seasonality_prior_scale: 10
        yearly_seasonality: true
        weekly_seasonality: true
        daily_seasonality: false

  features:
    date_features:
      - year
      - month
      - day
      - day_of_week
      - quarter
      - week_of_year
      - is_weekend
      - is_holiday
    lag_features:
      - 1
      - 2
      - 3
      - 7
      - 14
      - 21
      - 30
    rolling_features:
      windows:
        - 3
        - 7
        - 14
        - 21
        - 30
      functions:
        - mean
        - std
        - min
        - max
        - median

  validation:
    required_columns:
      - date
      - sales
      - store_id
      - product_id
    data_types:
      date: "datetime64[ns]"
      sales: float64
      store_id: object
      product_id: object
    value_ranges:
      sales:
        min: 0
        max: 1000000

  training:
    # train: 0.8; val: 0.1; test: 0.1
    test_size: 0.1
    validation_size: 0.1 
    cv_folds: 5
    metrics:
      - rmse
      - mae
      - mape
      - r2

  inference:
    batch_size: 1000
    prediction_horizon: 30
    confidence_intervals:
      - 0.8
      - 0.95

  monitoring:
    drift_detection:
      enabled: true
      method: kolmogorov_smirnov
      threshold: 0.1
    performance_monitoring:
      enabled: true
      alert_threshold:
        rmse: 1000
        mape: 0.2
