FROM python:3.12-slim

# Install MLflow and required dependencies
RUN pip install mlflow==3.3.2 psycopg2-binary boto3==1.40.21

# Set default environment variables (can be overridden at runtime)
ENV MLFLOW_PORT=5001 \
    MLFLOW_HOST=0.0.0.0

EXPOSE 5001

# Use bash to allow environment variable expansion
ENTRYPOINT ["bash", "-c"]
CMD ["mlflow server --host $MLFLOW_HOST --port $MLFLOW_PORT --backend-store-uri $MLFLOW_DB_URI --default-artifact-root $MLFLOW_ARTIFACT_ROOT --serve-artifacts"]
